### ISSUE TITLE
Clash config is broken.

### ISSUE THREAD

**Issue by AliKHaliliT** [mahdibland/V2RayAggregator#9]
Hi,

The clash config is broken because the clash client does not support ciphers:
- aes-256-cfb
- chacha20-poly1305

in shadowsocks links. 

Also, because it does not support tls = False in Vmess links.

I tried to locate the code, edit and then create a pull request, but I could not work around the code as it had low to no comments. 

This is what I am doing right now as a temporary fix:

```
import requests
import yaml


response = requests.get('https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/sub_merge_yaml.yml')


proxy_list = yaml.load(response.text, Loader=yaml.FullLoader)


for proxy in proxy_list["proxies"]:

    if proxy["type"] == "ss":
        if proxy["cipher"] == "aes-256-cfb" or proxy["cipher"] == "chacha20-poly1305":
            proxy_list["proxies"].remove(proxy)
    elif proxy["type"] == "vmess":
        if proxy["tls"] == False:
            proxy_list["proxies"].remove(proxy)


with open('assets/necessaryFiles/AggCleaned.yml', 'w') as f:
    yaml.dump(proxy_list, f)
```

**Comment by dickymuliafiqri** [comment]
@AliKHaliliT I would suggest u to use my api

fool.azurewebsites.net
But unfortunately, there's no english for now due to very early development phase and low of man resource. To be honest, translator needed 😉

Here's the example
fool.azurewebsites.net/get?vpn=vmess&cdn=hohm.microsoft.com&sni=safebrowsing.google.com&tls=1

This would give you vmess account with tls. ofc there's lot of query to be used.

However, shadowsocks isn't ready yet. But i already dump it.
Check another repo on my org if you interrested

**Comment by AliKHaliliT** [comment]
@dickymuliafiqri I'll check it out.

**Comment by mahdibland** [comment]
> Hi,
> 
> The clash config is broken because the clash client does not support ciphers:
> 
> * aes-256-cfb
> * chacha20-poly1305
> 
> in shadowsocks links.
> 
> Also, because it does not support tls = False in Vmess links.
> 
> I tried to locate the code, edit and then create a pull request, but I could not work around the code as it had low to no comments.
> 
> This is what I am doing right now as a temporary fix:
> 
> ```
> import requests
> import yaml
> 
> 
> response = requests.get('https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/sub_merge_yaml.yml')
> 
> 
> proxy_list = yaml.load(response.text, Loader=yaml.FullLoader)
> 
> 
> for proxy in proxy_list["proxies"]:
> 
>     if proxy["type"] == "ss":
>         if proxy["cipher"] == "aes-256-cfb" or proxy["cipher"] == "chacha20-poly1305":
>             proxy_list["proxies"].remove(proxy)
>     elif proxy["type"] == "vmess":
>         if proxy["tls"] == False:
>             proxy_list["proxies"].remove(proxy)
> 
> 
> with open('assets/necessaryFiles/AggCleaned.yml', 'w') as f:
>     yaml.dump(proxy_list, f)
> ```

Hi,
in shadowsocks configuration, "aes-256-cfb" cipher is supported. the only common cipher that is not supported in shadowsocks configuration is "chacha20-poly1305". [official document](https://github.com/Dreamacro/clash/wiki/configuration)

also in vmess configuration "TLS" option can be set as "False". the problem is when the node is using "h2" or "grpc" network. in these cases, the "TLS" option must be set to "True"

In addition to the above problems, in some nodes, the format of UUID is wrong or has a different length than 36. 

I modified the code to eliminate all nodes with one of the above problems.

**Comment by AliKHaliliT** [comment]
Thanks. The clash file is fixed. Closing the issue.
